fix(action): Invoke `uv` binary not module
[Issue]
CI jobs failing due to the following error:
```
/opt/hostedtoolcache/Python/3.10.18/x64/bin/python3: No module named uv
Error: Process completed with exit code 1.
```

[Fix]
Invoke `uv` binary installed and set up by action@setup-uv.
UV isn't installed as a package, hence cannot be invoked as -m (module)

Signed-off-by: Eugene Mwangi <mwangi.em37@gmail.com>