fix(setup-uv): Use overrides file over package
[Issue]
GHA build failing due to error on step (Install CI dependencies):
```
error: File not found: `uv;`
```

[Cause]
uv's install interface expects a file passed to --overrides flag.

[Fix]
Create and pass overrides file to ignore uv from dependency tree

[Note]
The overrides file could have been added to requirements/
which would be more persistent and centralized, however,
no need is seen, for now.

Signed-off-by: Eugene Mwangi <mwangi.em37@gmail.com>